language: python
python:
  - "2.6"
  - "2.7"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install --use-mirrors --quiet argparse; fi
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
script: 
  - nosetests petrarch/test.py
