language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq gfortran libatlas-base-dev python-numpy
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install --use-mirrors --quiet argparse; fi
# command to install dependencies
install:
  - pip install PyYAML joblib nltk simplejson --use-mirrors
script: 
  - nosetests petrarch/test.py
